using Xunit;

namespace ClinicManagementSystem.EntityFrameworkCore;

[CollectionDefinition(ClinicManagementSystemTestConsts.CollectionDefinitionName)]
public class ClinicManagementSystemEntityFrameworkCoreCollection : ICollectionFixture<ClinicManagementSystemEntityFrameworkCoreFixture>
{

}
