using ClinicManagementSystem.EntityFrameworkCore;
using Xunit;

namespace ClinicManagementSystem.EntityFrameworkCore;

public class ClinicManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ClinicManagementSystemEntityFrameworkCoreFixture>
{

}
