openapi: 3.0.3
info:
  title: Student Management API
  description: CRUD operations for Student Management with multi-tenant support
  version: 1.0.0

servers:
  - url: https://localhost:44324/api/app
    description: Development server

paths:
  /students:
    get:
      summary: Get paginated list of students
      description: Returns students belonging to the current tenant with optional name filter
      operationId: getStudentList
      tags:
        - Students
      parameters:
        - name: Filter
          in: query
          description: Search term for first name or last name
          required: false
          schema:
            type: string
        - name: Sorting
          in: query
          description: Sorting field and direction (e.g., "FirstName ASC")
          required: false
          schema:
            type: string
        - name: SkipCount
          in: query
          description: Number of records to skip (for pagination)
          required: false
          schema:
            type: integer
            default: 0
        - name: MaxResultCount
          in: query
          description: Maximum records to return
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedStudentResultDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions

    post:
      summary: Create a new student
      description: Creates a student in the current tenant. Student must be 18+ years old.
      operationId: createStudent
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudentDto'
      responses:
        '200':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '400':
          description: Validation error (including age < 18)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteServiceErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions

  /students/{id}:
    get:
      summary: Get student by ID
      description: Returns a single student if it belongs to the current tenant
      operationId: getStudent
      tags:
        - Students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Student not found (or belongs to different tenant)

    put:
      summary: Update student
      description: Updates an existing student. Student must remain 18+ years old.
      operationId: updateStudent
      tags:
        - Students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStudentDto'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDto'
        '400':
          description: Validation error (including age < 18)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoteServiceErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Student not found (or belongs to different tenant)

    delete:
      summary: Delete student (soft delete)
      description: Soft deletes a student belonging to the current tenant
      operationId: deleteStudent
      tags:
        - Students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Student deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Student not found (or belongs to different tenant)

components:
  schemas:
    StudentDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        age:
          type: integer
          description: Calculated age based on date of birth
        email:
          type: string
          format: email
          nullable: true
        phoneNumber:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        creationTime:
          type: string
          format: date-time
      required:
        - id
        - firstName
        - lastName
        - dateOfBirth
        - age
        - creationTime

    CreateStudentDto:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 64
        lastName:
          type: string
          maxLength: 64
        dateOfBirth:
          type: string
          format: date
          description: Must result in age 18+ at time of registration
        email:
          type: string
          format: email
          maxLength: 256
          nullable: true
          description: Must be unique within the tenant if provided
        phoneNumber:
          type: string
          maxLength: 20
          nullable: true
        address:
          type: string
          maxLength: 512
          nullable: true
      required:
        - firstName
        - lastName
        - dateOfBirth

    UpdateStudentDto:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 64
        lastName:
          type: string
          maxLength: 64
        dateOfBirth:
          type: string
          format: date
          description: Must result in age 18+ at time of update
        email:
          type: string
          format: email
          maxLength: 256
          nullable: true
        phoneNumber:
          type: string
          maxLength: 20
          nullable: true
        address:
          type: string
          maxLength: 512
          nullable: true
      required:
        - firstName
        - lastName
        - dateOfBirth

    PagedStudentResultDto:
      type: object
      properties:
        totalCount:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/StudentDto'
      required:
        - totalCount
        - items

    RemoteServiceErrorResponse:
      type: object
      description: ABP standard error response
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code (e.g., "ClinicManagement:Student:MustBe18OrOlder")
            message:
              type: string
              description: Localized error message
            details:
              type: string
              nullable: true
            validationErrors:
              type: array
              nullable: true
              items:
                type: object
                properties:
                  message:
                    type: string
                  members:
                    type: array
                    items:
                      type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OpenIddict JWT token

security:
  - bearerAuth: []

tags:
  - name: Students
    description: Student management operations
